version: "3.8"
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  core-api:
    build: apps/core-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
  bot-server:
    build: apps/bot-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
